baseurl = "https://fjjreal.github.io/"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "JunJian Feng"
theme = "dream"



# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true


# Copyright = "<p>4564</p>" # needCopyright & params.headerBottomText 不需要

[params]
  # 备案
  #needCopyright = true

  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "JunJian Feng"
  # description = ""
  avatar = "/img/avatar.jpeg"
  motto = "voojo"
  # categoriesLimitInHeader = 6
  headerTitle = "JunJian Feng 分享站"
  headerBottomText = "<p>4564headerBottomText</p>"

  rss = true

  # utterancesRepo = ""

  #valine = true
  LEANCLOUD_APP_ID = "83stadr63Tq81NB9uBkqGOxp-gzGzoHsz"
  LEANCLOUD_APP_KEY = "L5d68syrmwY3A8GHQRfwNER1"
  LEANCLOUD_APP_placeholder = "说点什么吧..."
  LEANCLOUD_APP_visitor = true

  github = "fjjreal"
  wechat = "code1024996"
  qq     = "328957143"
  email = "328957143@qq.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true
